[package]
name = "regcomms"
version = "0.1.0"
edition = "2024"

[features]
embedded_hal = ["embedded-hal"]
embedded-hal = ["dep:embedded-hal"]

[dependencies]
embedded-hal = { version = "1.0.0", optional = true }
