[package]
name = "reg_comms_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
clap_derive = "4.5.32"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
stringcase = "0.4.0"
